 /* SAS PROGRAM: CONVERT PRE-REGISTRATION FLAT FILE TO CSV FORMAT */

OPTIONS ERRORCHECK=STRICT;

%MACRO CSVIT(FLAG, VARI, RECORD, FIN);
* ;
 LENGTH RECORD $1200;
 LENGTH TEMP $300;
 LENGTH N $8;
 LENGTH D $2;
 RETAIN RECORD ' ';
 RETAIN QT '"';
 RETAIN CM ',';
 RETAIN DI '.';
 RETAIN QQ 'QQ';
 RETAIN JJ 'JJ';
 RETAIN KK 'KK';
 RETAIN FI 'FF';
 RETAIN FS 'FS';
 RETAIN AM 'AM';
 RETAIN AS 'AS';
* ;
 CM = ',';
 DI = '.';
 LVAR = LENGTH(VARI);
 IF FLAG = QQ THEN
 DO;
 TEMP = QT || SUBSTR(VARI,1,LVAR) ||
                        QT || CM;
 END;
 IF FLAG = JJ THEN
 DO;
 TEMP = QT || STRIP(SUBSTR(VARI,1,LVAR)) ||
                        QT || CM;
 END;
 IF FLAG = KK THEN
 DO;
  TEMP = QT || STRIP(SUBSTR(VARI,1,LVAR)) || QT;
 END;
 IF FLAG = AM THEN
 DO;
  M = COMPRESS(VARI);
  L = LENGTH(M);
  IF (L > 2) THEN
  DO;
   N = SUBSTR(M,1,(L-2));
   D = SUBSTR(M,(L-1),2);
   TEMP = QT || COMPRESS(N) || COMPRESS(D) || QT || CM;
  END;
  IF (L <= 2) THEN
  DO;
   N = '0';
   IF M > 0 THEN
   DO;
     D = M;
   END;
   IF M = 0 THEN
   DO;
     D = '00';
   END;
   TEMP = QT || COMPRESS(N) || COMPRESS(D) || QT || CM;
  END;
 END;
 IF FLAG = AS THEN
 DO;
  M = COMPRESS(VARI);
  L = LENGTH(M);
  IF (L > 2) THEN
  DO;
   N = SUBSTR(M,1,(L-2));
   D = SUBSTR(M,(L-1),2);
   TEMP = QT || COMPRESS(N) || COMPRESS(D) || QT || CM;
  END;
  IF (L <= 2) THEN
  DO;
   N = '0';
   IF M > 0 THEN
   DO;
     D = M;
   END;
   IF M = 0 THEN
   DO;
     D = '00';
   END;
   TEMP = QT || COMPRESS(N) || COMPRESS(D) || QT || CM;
   TEMP1= COMPRESS(TEMP,'"');
   TEMP1= COMPRESS(TEMP1,',');
   IF TEMP1 = '000' THEN
   DO;
    TEMP=COMPRESS(TEMP,'0');
   END;
  END;
 END;
 IF FLAG = FI THEN
 DO;
  TEMP = QT || SUBSTR(VARI,1,LVAR) || QT;
 END;
 IF FLAG = FS THEN
 DO;
  TEMP = QT || SUBSTR(VARI,1,LVAR) || QT;
  TEMP = COMPRESS(TEMP);
 END;
 LREC = LENGTH(RECORD);
 LTEMP = LENGTH(TEMP);
 RECORD = SUBSTR(RECORD,1,LREC) || SUBSTR(TEMP,1,LTEMP);
* ;
 %MEND CSVIT;
* ;

DATA INPUTF;
 INFILE INPUTF;
 LENGTH RECORD $1200.;
 LENGTH RECORD $1200.;
 LENGTH FLAG $2.;
 LENGTH VARI $256.;
 INPUT @1 KEY6  $6.
       @1 KEY9  $7.
       @1 KEY   $14. @;
 IF KEY6 = 'Header' THEN
 INPUT @1   XXXXX_BHDR_REC_IND           $6.
       @7   XXXXX_BHDR_FILE_ID           $30.
       @37  XXXXX_BHDR_DATE_FILE_SENT    $8.
       @45  XXXXX_BHDR_BLR_GRP_ID        $3.
       @48  XXXXX_BHDR_BLR_ID            $3.
       @51  XXXXX_BHDR_PROCESS_MODE      $1.
       @52  XXXXX_BHDR_VERSION           $3.;
 ELSE IF KEY = 'AddUserProfile' THEN
 INPUT @1    XXXXX_BDTL_AUPR_REC_TYPE     $14.
       @15   XXXXX_BDTL_AUPR_USER_ID      $16.
       @31   XXXXX_BDTL_AUPR_PASSWORD     $16.
       @47   XXXXX_BDTL_AUPR_FIRST_NM     $30.
       @77   XXXXX_BDTL_AUPR_LAST_NM      $30.
       @107  XXXXX_BDTL_AUPR_COMPANY_NM   $30.
       @137  XXXXX_BDTL_AUPR_COUNTRY      $03.
       @140  XXXXX_BDTL_AUPR_STREET_ADDR1 $50.
       @190  XXXXX_BDTL_AUPR_STREET_ADDR2 $50.
       @240  XXXXX_BDTL_AUPR_STREET_ADDR3 $50.
       @290  XXXXX_BDTL_AUPR_CITY         $30.
       @320  XXXXX_BDTL_AUPR_STATE        $02.
       @322  XXXXX_BDTL_AUPR_PROVINCE     $30.
       @352  XXXXX_BDTL_AUPR_ZIP_CD5      $05.
       @357  XXXXX_BDTL_AUPR_ZIP_CD4      $04.
       @361  XXXXX_BDTL_AUPR_POSTAL_CD      $10.
       @371  XXXXX_BDTL_AUPR_PHONE_NUM      $10.
       @381  XXXXX_BDTL_AUPR_INT_PHONE_NUM  $20.
       @401  XXXXX_BDTL_AUPR_EMAIL_ADDR     $256.
       @657  XXXXX_BDTL_AUPR_SHRDS_QUEST    $25.
       @682  XXXXX_BDTL_AUPR_SHRDS_RSP      $20.
       @702  XXXXX_BDTL_AUPR_CELL_PHONE     $10.
       @712  XXXXX_BDTL_AUPR_BILL_NOTF_ID   $01.
       @713  XXXXX_BDTL_AUPR_PAPR_LESS_BILL $01.
       @714  XXXXX_BDTL_AUPR_ACH_STATUS     $01.
       @715  XXXXX_BDTL_AUPR_CC_STATUS      $01.
       @716  XXXXX_BDTL_AUPR_ATM_STATUS     $01.;
 ELSE IF KEY = 'DeleteAuthoriz' THEN
 INPUT @1    XXXXX_BDTL_DAPR_REC_IND        $23.
       @24   XXXXX_BDTL_DAPR_USER_ID        $16.
       @40   XXXXX_BDTL_DAPR_BILLR_PROD_CD  $32.;
 ELSE IF KEY = 'AddPaymentInfo' THEN
 INPUT @1   XXXXX_BDTL_APIR_REC_IND         $14.
       @15  XXXXX_BDTL_APIR_USER_ID         $16.
       @31  XXXXX_BDTL_APIR_BILLR_PROD_CD   $32.
       @63  XXXXX_BDTL_APIR_DUE_DATE        $08.
       @71  XXXXX_BDTL_APIR_AMT_DUE         10.
       @81  XXXXX_BDTL_APIR_SALES_TAX_AMT   10.
       @91  XXXXX_BDTL_APIR_CUST_REF_NUM    $17.;
 ELSE IF KEY = 'UpdatePaymentI' THEN
 INPUT @1   XXXXX_BDTL_UPIR_REC_IND         $17.
       @18  XXXXX_BDTL_UPIR_USER_ID         $16.
       @34  XXXXX_BDTL_UPIR_BILLR_PROD_CD   $32.
       @66  XXXXX_BDTL_UPIR_DUE_DATE        $08.
       @74  XXXXX_BDTL_UPIR_AMT_DUE         10.
       @84  XXXXX_BDTL_UPIR_SALES_TAX_AMT   10.
       @94  XXXXX_BDTL_UPIR_CUST_REF_NUM    $17.;
 ELSE IF KEY = 'AddRecurringPa' THEN
 INPUT   @1 XXXXX_BDTL_ARPR_REC_IND        $19.
        @20 XXXXX_BDTL_ARPR_USER_ID        $16.
        @36 XXXXX_BDTL_ARPR_BILLR_PROD_CD  $32.
        @68 XXXXX_BDTL_ARPR_PYMT_TYPE_IND  $02.
        @70 XXXXX_BDTL_ARPR_PYMT_METH_IND  $03.
        @73 XXXXX_BDTL_ARPR_PYMT_AMOUNT    $10.
        @83 XXXXX_BDTL_ARPR_PYMT_FREQ      $15.
        @98 XXXXX_BDTL_ARPR_PYMT_DUR_IND   $15.
       @113 XXXXX_BDTL_ARPR_PYMT_EXPR_DT   $08.
       @121 XXXXX_BDTL_ARPR_NUM_OF_PYMT    $3.
       @124 XXXXX_BDTL_ARPR_FIRST_PYMT_DT  $08.
       @132 XXXXX_BDTL_ARPR_DY_MON_FST_PY  $02.
       @134 XXXXX_BDTL_ARPR_DY_MON_SEC_PY  $02.
       @136 XXXXX_BDTL_ARPR_THRES_HOLD_AMT $10.
       @146 XXXXX_BDTL_ARPR_ACCT_NICK_NM   $20.
       @166 XXXXX_BDTL_ARPR_BANK_RTN       $09.
       @175 XXXXX_BDTL_ARPR_ACCT_NUM       $17.
       @192 XXXXX_BDTL_ARPR_ACCT_TYPE      $01.
       @193 XXXXX_BDTL_ARPR_ACCT_CATG      $01.
       @194 XXXXX_BDTL_ARPR_CARD_TYPE      $04.
       @198 XXXXX_BDTL_ARPR_CARD_NUM       $19.
       @217 XXXXX_BDTL_ARPR_CARD_HLDR_NM   $50.
       @267 XXXXX_BDTL_ARPR_CARD_EXPR_DT   $04.
       @271 XXXXX_BDTL_ARPR_COUNTRY        $03.
       @274 XXXXX_BDTL_ARPR_STREET_ADDR1   $50.
       @324 XXXXX_BDTL_ARPR_STREET_ADDR2   $50.
       @374 XXXXX_BDTL_ARPR_STREET_ADDR3   $50.
       @424 XXXXX_BDTL_ARPR_CITY           $30.
       @454 XXXXX_BDTL_ARPR_STATE          $02.
       @456 XXXXX_BDTL_ARPR_PROVINCE       $30.
       @486 XXXXX_BDTL_ARPR_ZIP_CD5        $05.
       @491 XXXXX_BDTL_ARPR_ZIP_CD4        $04.
       @495 XXXXX_BDTL_ARPR_POSTAL_CD      $10.;
 ELSE IF KEY = 'StopRecurringP' THEN
 INPUT @1   XXXXX_BDTL_SRPR_REC_IND        $20.
       @21  XXXXX_BDTL_SRPR_USER_ID        $16.
       @37  XXXXX_BDTL_SRPR_BILLR_PROD_CD  $32.
       @69  XXXXX_BDTL_SRPR_RECUR_REF_ID   $17.;
 ELSE IF KEY = 'AddProductPara' THEN
 INPUT @1  XXXXX_BDTL_APPR_REC_IND         $19.
       @20 XXXXX_BDTL_APPR_USER_ID         $16.
       @36 XXXXX_BDTL_APPR_BILLR_PROD_CD   $32.
       @68 XXXXX_BDTL_APPR_PARMTR_NM       $26.
       @94 XXXXX_BDTL_APPR_PARMTR_VALUE    $50.;
 ELSE IF KEY9 = 'Trailer' THEN
  INPUT @1 XXXXX_BTLR_RECORD_IND      $7.
    @8 XXXXX_BTLR_ADD_USER_PROF_CNT    7.
   @15 XXXXX_BTLR_UPD_USER_PROF_CNT    7.
   @22 XXXXX_BTLR_DEL_USER_PROF_CNT    7.
   @29 XXXXX_BTLR_UPD_AUTH_PROD_CNT    7.
   @36 XXXXX_BTLR_DEL_AUTH_PROD_CNT    7.
   @43 XXXXX_BTLR_ADD_PYMT_INFO_CNT    7.
   @50 XXXXX_BTLR_UPD_PYMT_INFO_CNT    7.
   @57 XXXXX_BTLR_ADD_BANK_ACCT_CNT    7.
   @64 XXXXX_BTLR_UPD_BANK_ACCT_CNT    7.
   @71 XXXXX_BTLR_ADD_CRDC_ACCT_CNT    7.
   @78 XXXXX_BTLR_UPD_CRDC_ACCT_CNT    7.
   @85 XXXXX_BTLR_ADD_PRDC_PARM_CNT    7.
   @92 XXXXX_BTLR_UPD_PRDC_PARM_CNT    7.
   @99 XXXXX_BTLR_DEL_PRDC_PARM_CNT    7.
  @106 XXXXX_BTLR_ADD_RECR_PYMT_CNT    7.
  @113 XXXXX_BTLR_STP_RECR_PYMT_CNT    7.
  @120 XXXXX_BTLR_ADD_STMT_INFO_CNT    7.
  @127 XXXXX_BTLR_UPD_STMT_INFO_CNT    7.
  @134 XXXXX_BTLR_ADD_LVL3_REC_CNT     7.
  @141 XXXXX_BTLR_UPD_LVL3_REC_CNT     7.
  @148 XXXXX_BTLR_DEL_LVL3_REC_CNT     7.
  @155 XXXXX_BTLR_ADD_LINE_ITEM_CNT    7.
  @162 XXXXX_BTLR_UPD_LINE_ITEM_CNT    7.
  @169 XXXXX_BTLR_DEL_LINE_ITEM_CNT    7.
  @176 XXXXX_BTLR_ADD_ATM_CARD_CNT     7.
  @183 XXXXX_BTLR_UPD_ATM_CARD_CNT     7.;
 IF KEY6 = 'Header' THEN
 DO;
  FIN = ' ';
  RECORD = ' ';
  RECORD1= ' ';
  RECORD2= ' ';
  FLAG = 'QQ';
  VARI=XXXXX_BHDR_REC_IND;
  %CSVIT(FLAG,VARI,RECORD,FIN);
  VARI=XXXXX_BHDR_FILE_ID;
  %CSVIT(FLAG,VARI,RECORD,FIN);
  VARI=XXXXX_BHDR_DATE_FILE_SENT;
  %CSVIT(FLAG,VARI,RECORD,FIN);
  VARI=XXXXX_BHDR_BLR_GRP_ID;
  %CSVIT(FLAG,VARI,RECORD,FIN);
  VARI=XXXXX_BHDR_BLR_ID;
  %CSVIT(FLAG,VARI,RECORD,FIN);
  VARI=XXXXX_BHDR_PROCESS_MODE;
  %CSVIT(FLAG,VARI,RECORD,FIN);
  FLAG = 'FF';
  VARI=XXXXX_BHDR_VERSION;
  %CSVIT(FLAG,VARI,RECORD,FIN);
 END;
 ELSE IF KEY = 'AddUserProfile' THEN
 DO;
  FIN = ' ';
  RECORD = ' ';
  RECORD1= ' ';
  RECORD2= ' ';
  FLAG = 'JJ';
  VARI=XXXXX_BDTL_AUPR_REC_TYPE;
  %CSVIT(FLAG,VARI,RECORD,FIN);
  VARI=XXXXX_BDTL_AUPR_USER_ID;
  %CSVIT(FLAG,VARI,RECORD,FIN);
  VARI=XXXXX_BDTL_AUPR_PASSWORD;
  %CSVIT(FLAG,VARI,RECORD,FIN);
  VARI=XXXXX_BDTL_AUPR_FIRST_NM;
  %CSVIT(FLAG,VARI,RECORD,FIN);
  VARI=XXXXX_BDTL_AUPR_LAST_NM;
  %CSVIT(FLAG,VARI,RECORD,FIN);
  VARI=XXXXX_BDTL_AUPR_COMPANY_NM;
  %CSVIT(FLAG,VARI,RECORD,FIN);
  VARI=XXXXX_BDTL_AUPR_COUNTRY;
  %CSVIT(FLAG,VARI,RECORD,FIN);
  VARI=XXXXX_BDTL_AUPR_STREET_ADDR1;
  %CSVIT(FLAG,VARI,RECORD,FIN);
  VARI=XXXXX_BDTL_AUPR_STREET_ADDR2;
  %CSVIT(FLAG,VARI,RECORD,FIN);
  VARI=XXXXX_BDTL_AUPR_STREET_ADDR3;
  %CSVIT(FLAG,VARI,RECORD,FIN);
  VARI=XXXXX_BDTL_AUPR_CITY;
  %CSVIT(FLAG,VARI,RECORD,FIN);
  VARI=XXXXX_BDTL_AUPR_STATE;
  %CSVIT(FLAG,VARI,RECORD,FIN);
  VARI=XXXXX_BDTL_AUPR_PROVINCE;
  %CSVIT(FLAG,VARI,RECORD,FIN);
  VARI=XXXXX_BDTL_AUPR_ZIP_CD5;
  %CSVIT(FLAG,VARI,RECORD,FIN);
  VARI=XXXXX_BDTL_AUPR_ZIP_CD4;
  %CSVIT(FLAG,VARI,RECORD,FIN);
  VARI=XXXXX_BDTL_AUPR_POSTAL_CD;
  %CSVIT(FLAG,VARI,RECORD,FIN);
  VARI=XXXXX_BDTL_AUPR_PHONE_NUM;
  %CSVIT(FLAG,VARI,RECORD,FIN);
  VARI=XXXXX_BDTL_AUPR_INT_PHONE_NUM;
  %CSVIT(FLAG,VARI,RECORD,FIN);
  VARI=XXXXX_BDTL_AUPR_EMAIL_ADDR;
  %CSVIT(FLAG,VARI,RECORD,FIN);
  VARI=XXXXX_BDTL_AUPR_SHRDS_QUEST;
  %CSVIT(FLAG,VARI,RECORD,FIN);
  VARI=XXXXX_BDTL_AUPR_SHRDS_RSP;
  %CSVIT(FLAG,VARI,RECORD,FIN);
  VARI=XXXXX_BDTL_AUPR_CELL_PHONE;
  %CSVIT(FLAG,VARI,RECORD,FIN);
  VARI=XXXXX_BDTL_AUPR_BILL_NOTF_ID;
  %CSVIT(FLAG,VARI,RECORD,FIN);
  VARI=XXXXX_BDTL_AUPR_PAPR_LESS_BILL;
  %CSVIT(FLAG,VARI,RECORD,FIN);
  VARI=XXXXX_BDTL_AUPR_ACH_STATUS;
  %CSVIT(FLAG,VARI,RECORD,FIN);
  VARI=XXXXX_BDTL_AUPR_CC_STATUS;
  %CSVIT(FLAG,VARI,RECORD,FIN);
  VARI=XXXXX_BDTL_AUPR_ATM_STATUS;
  FLAG = 'KK';
  %CSVIT(FLAG,VARI,RECORD,FIN);
 END;
 ELSE IF KEY = 'DeleteAuthoriz' THEN
 DO;
  FIN = ' ';
  RECORD = ' ';
  RECORD1= ' ';
  RECORD2= ' ';
  FLAG = 'JJ';
  VARI=XXXXX_BDTL_DAPR_REC_IND;
  %CSVIT(FLAG,VARI,RECORD,FIN);
  VARI=XXXXX_BDTL_DAPR_USER_ID;
  %CSVIT(FLAG,VARI,RECORD,FIN);
  VARI=XXXXX_BDTL_DAPR_BILLR_PROD_CD;
  FLAG = 'KK';
  %CSVIT(FLAG,VARI,RECORD,FIN);
 END;
 ELSE IF KEY = 'AddPaymentInfo' THEN
 DO;
  FIN = ' ';
  RECORD = ' ';
  RECORD1= ' ';
  RECORD2= ' ';
  FLAG = 'QQ';
  VARI=XXXXX_BDTL_APIR_REC_IND;
  %CSVIT(FLAG,VARI,RECORD,FIN);
  VARI=XXXXX_BDTL_APIR_USER_ID;
  %CSVIT(FLAG,VARI,RECORD,FIN);
  VARI=XXXXX_BDTL_APIR_BILLR_PROD_CD;
  %CSVIT(FLAG,VARI,RECORD,FIN);
  VARI=XXXXX_BDTL_APIR_DUE_DATE;
  %CSVIT(FLAG,VARI,RECORD,FIN);
  FLAG = 'AM';
  VARI=XXXXX_BDTL_APIR_AMT_DUE;
  %CSVIT(FLAG,VARI,RECORD,FIN);
  FLAG = 'AS';
  VARI=XXXXX_BDTL_APIR_SALES_TAX_AMT;
  %CSVIT(FLAG,VARI,RECORD,FIN);
  VARI=XXXXX_BDTL_APIR_CUST_REF_NUM;
  FLAG = 'FS';
  %CSVIT(FLAG,VARI,RECORD,FIN);
 END;
 ELSE IF KEY = 'UpdatePaymentI' THEN
 DO;
  FIN = ' ';
  RECORD = ' ';
  RECORD1= ' ';
  RECORD2= ' ';
  FLAG = 'QQ';
  VARI=XXXXX_BDTL_UPIR_REC_IND;
  %CSVIT(FLAG,VARI,RECORD,FIN);
  VARI=XXXXX_BDTL_UPIR_USER_ID;
  %CSVIT(FLAG,VARI,RECORD,FIN);
  VARI=XXXXX_BDTL_UPIR_BILLR_PROD_CD;
  %CSVIT(FLAG,VARI,RECORD,FIN);
  VARI=XXXXX_BDTL_UPIR_DUE_DATE;
  %CSVIT(FLAG,VARI,RECORD,FIN);
  FLAG = 'AM';
  VARI=XXXXX_BDTL_UPIR_AMT_DUE;
  %CSVIT(FLAG,VARI,RECORD,FIN);
  FLAG = 'AS';
  VARI=XXXXX_BDTL_UPIR_SALES_TAX_AMT;
  %CSVIT(FLAG,VARI,RECORD,FIN);
  VARI=XXXXX_BDTL_UPIR_CUST_REF_NUM;
  FLAG = 'FS';
  %CSVIT(FLAG,VARI,RECORD,FIN);
 END;
 ELSE IF KEY = 'AddRecurringPa' THEN
 DO;
  FIN = ' ';
  RECORD = ' ';
  RECORD1= ' ';
  RECORD2= ' ';
  FLAG = 'JJ';
  VARI=XXXXX_BDTL_ARPR_REC_IND;
  %CSVIT(FLAG,VARI,RECORD,FIN);
  VARI=XXXXX_BDTL_ARPR_USER_ID;
  %CSVIT(FLAG,VARI,RECORD,FIN);
  VARI=XXXXX_BDTL_ARPR_BILLR_PROD_CD;
  %CSVIT(FLAG,VARI,RECORD,FIN);
  VARI=XXXXX_BDTL_ARPR_PYMT_TYPE_IND;
  %CSVIT(FLAG,VARI,RECORD,FIN);
  VARI=XXXXX_BDTL_ARPR_PYMT_METH_IND;
  %CSVIT(FLAG,VARI,RECORD,FIN);
  VARI=XXXXX_BDTL_ARPR_PYMT_AMOUNT;
  %CSVIT(FLAG,VARI,RECORD,FIN);
  VARI=XXXXX_BDTL_ARPR_PYMT_FREQ;
  %CSVIT(FLAG,VARI,RECORD,FIN);
  VARI=XXXXX_BDTL_ARPR_PYMT_DUR_IND;
  %CSVIT(FLAG,VARI,RECORD,FIN);
  VARI=XXXXX_BDTL_ARPR_PYMT_EXPR_DT;
  %CSVIT(FLAG,VARI,RECORD,FIN);
  VARI=XXXXX_BDTL_ARPR_NUM_OF_PYMT;
  %CSVIT(FLAG,VARI,RECORD,FIN);
  VARI=XXXXX_BDTL_ARPR_FIRST_PYMT_DT;
  %CSVIT(FLAG,VARI,RECORD,FIN);
  VARI=XXXXX_BDTL_ARPR_DY_MON_FST_PY;
  %CSVIT(FLAG,VARI,RECORD,FIN);
  VARI=XXXXX_BDTL_ARPR_DY_MON_SEC_PY;
  %CSVIT(FLAG,VARI,RECORD,FIN);
  VARI=XXXXX_BDTL_ARPR_THRES_HOLD_AMT;
  %CSVIT(FLAG,VARI,RECORD,FIN);
  VARI=XXXXX_BDTL_ARPR_ACCT_NICK_NM;
  %CSVIT(FLAG,VARI,RECORD,FIN);
  VARI=XXXXX_BDTL_ARPR_BANK_RTN;
  %CSVIT(FLAG,VARI,RECORD,FIN);
  VARI=XXXXX_BDTL_ARPR_ACCT_NUM;
  %CSVIT(FLAG,VARI,RECORD,FIN);
  VARI=XXXXX_BDTL_ARPR_ACCT_TYPE;
  %CSVIT(FLAG,VARI,RECORD,FIN);
  VARI=XXXXX_BDTL_ARPR_ACCT_CATG;
  %CSVIT(FLAG,VARI,RECORD,FIN);
  VARI=XXXXX_BDTL_ARPR_CARD_TYPE;
  %CSVIT(FLAG,VARI,RECORD,FIN);
  VARI=XXXXX_BDTL_ARPR_CARD_NUM;
  %CSVIT(FLAG,VARI,RECORD,FIN);
  VARI=XXXXX_BDTL_ARPR_CARD_HLDR_NM;
  %CSVIT(FLAG,VARI,RECORD,FIN);
  VARI=XXXXX_BDTL_ARPR_CARD_EXPR_DT;
  %CSVIT(FLAG,VARI,RECORD,FIN);
  VARI=XXXXX_BDTL_ARPR_COUNTRY;
  %CSVIT(FLAG,VARI,RECORD,FIN);
  VARI=XXXXX_BDTL_ARPR_STREET_ADDR1;
  %CSVIT(FLAG,VARI,RECORD,FIN);
  VARI=XXXXX_BDTL_ARPR_STREET_ADDR2;
  %CSVIT(FLAG,VARI,RECORD,FIN);
  VARI=XXXXX_BDTL_ARPR_STREET_ADDR3;
  %CSVIT(FLAG,VARI,RECORD,FIN);
  VARI=XXXXX_BDTL_ARPR_CITY;
  %CSVIT(FLAG,VARI,RECORD,FIN);
  VARI=XXXXX_BDTL_ARPR_STATE;
  %CSVIT(FLAG,VARI,RECORD,FIN);
  VARI=XXXXX_BDTL_ARPR_PROVINCE;
  %CSVIT(FLAG,VARI,RECORD,FIN);
  VARI=XXXXX_BDTL_ARPR_ZIP_CD5;
  %CSVIT(FLAG,VARI,RECORD,FIN);
  VARI=XXXXX_BDTL_ARPR_ZIP_CD4;
  %CSVIT(FLAG,VARI,RECORD,FIN);
  VARI=XXXXX_BDTL_ARPR_POSTAL_CD;
  FLAG = 'KK';
  %CSVIT(FLAG,VARI,RECORD,FIN);
 END;
 ELSE IF KEY = 'StopRecurringP' THEN
 DO;
  FIN = ' ';
  RECORD = ' ';
  RECORD1= ' ';
  RECORD2= ' ';
  FLAG = 'QQ';
  VARI=XXXXX_BDTL_SRPR_REC_IND;
  %CSVIT(FLAG,VARI,RECORD,FIN);
  VARI=XXXXX_BDTL_SRPR_USER_ID;
  %CSVIT(FLAG,VARI,RECORD,FIN);
  VARI=XXXXX_BDTL_SRPR_BILLR_PROD_CD;
  %CSVIT(FLAG,VARI,RECORD,FIN);
  VARI=XXXXX_BDTL_SRPR_RECUR_REF_ID;
  FLAG = 'FF';
  %CSVIT(FLAG,VARI,RECORD,FIN);
 END;
 ELSE IF KEY = 'AddProductPara' THEN
 DO;
  FIN = ' ';
  RECORD = ' ';
  RECORD1= ' ';
  RECORD2= ' ';
  FLAG = 'JJ';
  VARI=XXXXX_BDTL_APPR_REC_IND;
  %CSVIT(FLAG,VARI,RECORD,FIN);
  VARI=XXXXX_BDTL_APPR_USER_ID;
  %CSVIT(FLAG,VARI,RECORD,FIN);
  VARI=XXXXX_BDTL_APPR_BILLR_PROD_CD;
  %CSVIT(FLAG,VARI,RECORD,FIN);
  VARI=XXXXX_BDTL_APPR_PARMTR_NM;
  %CSVIT(FLAG,VARI,RECORD,FIN);
  VARI=XXXXX_BDTL_APPR_PARMTR_VALUE;
  FLAG = 'KK';
  %CSVIT(FLAG,VARI,RECORD,FIN);
 END;
 ELSE IF KEY9 = 'Trailer' THEN
 DO;
  FIN = ' ';
  RECORD = ' ';
  RECORD1= ' ';
  RECORD2= ' ';
  FLAG = 'QQ';
  VARI=COMPRESS(XXXXX_BTLR_RECORD_IND);
  %CSVIT(FLAG,VARI,RECORD,FIN);
  VARI=COMPRESS(XXXXX_BTLR_ADD_USER_PROF_CNT);
  %CSVIT(FLAG,VARI,RECORD,FIN);
  VARI=COMPRESS(XXXXX_BTLR_UPD_USER_PROF_CNT);
  %CSVIT(FLAG,VARI,RECORD,FIN);
  VARI=COMPRESS(XXXXX_BTLR_DEL_USER_PROF_CNT);
  %CSVIT(FLAG,VARI,RECORD,FIN);
  VARI=COMPRESS(XXXXX_BTLR_UPD_AUTH_PROD_CNT);
  %CSVIT(FLAG,VARI,RECORD,FIN);
  VARI=COMPRESS(XXXXX_BTLR_DEL_AUTH_PROD_CNT);
  %CSVIT(FLAG,VARI,RECORD,FIN);
  VARI=COMPRESS(XXXXX_BTLR_ADD_PYMT_INFO_CNT);
  %CSVIT(FLAG,VARI,RECORD,FIN);
  VARI=COMPRESS(XXXXX_BTLR_UPD_PYMT_INFO_CNT);
  %CSVIT(FLAG,VARI,RECORD,FIN);
  VARI=COMPRESS(XXXXX_BTLR_ADD_BANK_ACCT_CNT);
  %CSVIT(FLAG,VARI,RECORD,FIN);
  VARI=COMPRESS(XXXXX_BTLR_UPD_BANK_ACCT_CNT);
  %CSVIT(FLAG,VARI,RECORD,FIN);
  VARI=COMPRESS(XXXXX_BTLR_ADD_CRDC_ACCT_CNT);
  %CSVIT(FLAG,VARI,RECORD,FIN);
  VARI=COMPRESS(XXXXX_BTLR_UPD_CRDC_ACCT_CNT);
  %CSVIT(FLAG,VARI,RECORD,FIN);
  VARI=COMPRESS(XXXXX_BTLR_ADD_PRDC_PARM_CNT);
  %CSVIT(FLAG,VARI,RECORD,FIN);
  VARI=COMPRESS(XXXXX_BTLR_UPD_PRDC_PARM_CNT);
  %CSVIT(FLAG,VARI,RECORD,FIN);
  VARI=COMPRESS(XXXXX_BTLR_DEL_PRDC_PARM_CNT);
  %CSVIT(FLAG,VARI,RECORD,FIN);
  VARI=COMPRESS(XXXXX_BTLR_ADD_RECR_PYMT_CNT);
  %CSVIT(FLAG,VARI,RECORD,FIN);
  VARI=COMPRESS(XXXXX_BTLR_STP_RECR_PYMT_CNT);
  %CSVIT(FLAG,VARI,RECORD,FIN);
  VARI=COMPRESS(XXXXX_BTLR_ADD_STMT_INFO_CNT);
  %CSVIT(FLAG,VARI,RECORD,FIN);
  VARI=COMPRESS(XXXXX_BTLR_UPD_STMT_INFO_CNT);
  %CSVIT(FLAG,VARI,RECORD,FIN);
  VARI=COMPRESS(XXXXX_BTLR_ADD_LVL3_REC_CNT);
  %CSVIT(FLAG,VARI,RECORD,FIN);
  VARI=COMPRESS(XXXXX_BTLR_UPD_LVL3_REC_CNT);
  %CSVIT(FLAG,VARI,RECORD,FIN);
  VARI=COMPRESS(XXXXX_BTLR_DEL_LVL3_REC_CNT);
  %CSVIT(FLAG,VARI,RECORD,FIN);
  VARI=COMPRESS(XXXXX_BTLR_ADD_LINE_ITEM_CNT);
  %CSVIT(FLAG,VARI,RECORD,FIN);
  VARI=COMPRESS(XXXXX_BTLR_UPD_LINE_ITEM_CNT);
  %CSVIT(FLAG,VARI,RECORD,FIN);
  VARI=COMPRESS(XXXXX_BTLR_DEL_LINE_ITEM_CNT);
  %CSVIT(FLAG,VARI,RECORD,FIN);
  VARI=COMPRESS(XXXXX_BTLR_ADD_ATM_CARD_CNT);
  %CSVIT(FLAG,VARI,RECORD,FIN);
  VARI=COMPRESS(XXXXX_BTLR_UPD_ATM_CARD_CNT);
  FLAG = 'FF';
  %CSVIT(FLAG,VARI,RECORD,FIN);
 END;
 ELSE
 DO;
 RECORD = "INVALID RECORD READ";
 END;

 FILE OUTF;
 PUT @1 RECORD;
RUN;
