--------------------------------------------------------
--  File created - Friday-February-10-2023   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table AWD_SRCE_TYPE
--------------------------------------------------------

  CREATE TABLE "SWB"."AWD_SRCE_TYPE" 
   (	"NAME" VARCHAR2(50 BYTE), 
	"DESC" VARCHAR2(150 BYTE), 
	 CONSTRAINT "AWD_SRCE_TYPE_PK" PRIMARY KEY ("NAME") ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  ORGANIZATION INDEX NOCOMPRESS PCTFREE 10 INITRANS 2 MAXTRANS 255 LOGGING
  STORAGE(INITIAL 131072 NEXT 131072 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA_SMALL" 
 PCTTHRESHOLD 50;
  GRANT SELECT ON "SWB"."AWD_SRCE_TYPE" TO "T40HC44";
  GRANT UPDATE ON "SWB"."AWD_SRCE_TYPE" TO "SWB_ADMIN";
  GRANT SELECT ON "SWB"."AWD_SRCE_TYPE" TO "SWB_ADMIN";
  GRANT INSERT ON "SWB"."AWD_SRCE_TYPE" TO "SWB_ADMIN";
  GRANT DELETE ON "SWB"."AWD_SRCE_TYPE" TO "SWB_ADMIN";
  GRANT ALTER ON "SWB"."AWD_SRCE_TYPE" TO "SWB_ADMIN";
  GRANT SELECT ON "SWB"."AWD_SRCE_TYPE" TO "SWB_QUERY";
--------------------------------------------------------
--  DDL for Table AWD_SRCE_TYPE_063013
--------------------------------------------------------

  CREATE TABLE "SWB"."AWD_SRCE_TYPE_063013" 
   (	"NAME" VARCHAR2(50 BYTE), 
	"DESC" VARCHAR2(150 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table AWD_WRK_TYPE
--------------------------------------------------------

  CREATE TABLE "SWB"."AWD_WRK_TYPE" 
   (	"WRK_TYPE" CHAR(10 BYTE), 
	"WRK_TYPE_DESC" VARCHAR2(50 BYTE), 
	"MOD_DT" DATE DEFAULT SYSDATE, 
	"MOD_BY" VARCHAR2(30 BYTE) DEFAULT USER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 131072 NEXT 131072 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA_SMALL" ;
  GRANT SELECT ON "SWB"."AWD_WRK_TYPE" TO "T40HC44";
  GRANT UPDATE ON "SWB"."AWD_WRK_TYPE" TO "SWB_ADMIN";
  GRANT SELECT ON "SWB"."AWD_WRK_TYPE" TO "SWB_ADMIN";
  GRANT INSERT ON "SWB"."AWD_WRK_TYPE" TO "SWB_ADMIN";
  GRANT DELETE ON "SWB"."AWD_WRK_TYPE" TO "SWB_ADMIN";
  GRANT ALTER ON "SWB"."AWD_WRK_TYPE" TO "SWB_ADMIN";
--------------------------------------------------------
--  DDL for Table CORR_PRT_METH_ALLW
--------------------------------------------------------

  CREATE TABLE "SWB"."CORR_PRT_METH_ALLW" 
   (	"CORR_TYPE_ID" NUMBER(*,0), 
	"PRT_OPT_ID" NUMBER(*,0), 
	"PRT_METH_ID" NUMBER(*,0), 
	"VCSR_PRT_METH_IND" CHAR(1 BYTE), 
	"DFLT_PRT_METH_IND" CHAR(1 BYTE), 
	"MOD_DT" DATE DEFAULT SYSDATE, 
	"MOD_BY" VARCHAR2(30 BYTE) DEFAULT USER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 131072 NEXT 131072 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA_SMALL" ;
  GRANT SELECT ON "SWB"."CORR_PRT_METH_ALLW" TO "T40HC44";
  GRANT UPDATE ON "SWB"."CORR_PRT_METH_ALLW" TO "SWB_ADMIN";
  GRANT SELECT ON "SWB"."CORR_PRT_METH_ALLW" TO "SWB_ADMIN";
  GRANT INSERT ON "SWB"."CORR_PRT_METH_ALLW" TO "SWB_ADMIN";
  GRANT DELETE ON "SWB"."CORR_PRT_METH_ALLW" TO "SWB_ADMIN";
  GRANT ALTER ON "SWB"."CORR_PRT_METH_ALLW" TO "SWB_ADMIN";
--------------------------------------------------------
--  DDL for Table CORR_PRT_OPT_ALLW
--------------------------------------------------------

  CREATE TABLE "SWB"."CORR_PRT_OPT_ALLW" 
   (	"CORR_TYPE_ID" NUMBER(*,0), 
	"PRT_OPT_ID" NUMBER(*,0), 
	"VCSR_PRT_OPT_IND" CHAR(1 BYTE), 
	"CHG_ALLW_IND" CHAR(1 BYTE), 
	"DFLT_PRT_OPT_IND" CHAR(1 BYTE), 
	"MOD_DT" DATE DEFAULT SYSDATE, 
	"MOD_BY" VARCHAR2(30 BYTE) DEFAULT USER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 131072 NEXT 131072 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA_SMALL" ;
  GRANT SELECT ON "SWB"."CORR_PRT_OPT_ALLW" TO "T40HC44";
  GRANT UPDATE ON "SWB"."CORR_PRT_OPT_ALLW" TO "SWB_ADMIN";
  GRANT SELECT ON "SWB"."CORR_PRT_OPT_ALLW" TO "SWB_ADMIN";
  GRANT INSERT ON "SWB"."CORR_PRT_OPT_ALLW" TO "SWB_ADMIN";
  GRANT DELETE ON "SWB"."CORR_PRT_OPT_ALLW" TO "SWB_ADMIN";
  GRANT ALTER ON "SWB"."CORR_PRT_OPT_ALLW" TO "SWB_ADMIN";
--------------------------------------------------------
--  DDL for Table CORR_TYPE
--------------------------------------------------------

  CREATE TABLE "SWB"."CORR_TYPE" 
   (	"CORR_TYPE_ID" NUMBER(*,0), 
	"WRK_TYPE" CHAR(10 BYTE), 
	"DOCM_TYPE_ID" NUMBER(*,0), 
	"CORR_DESC" VARCHAR2(50 BYTE), 
	"DFS_INTG_IND" CHAR(1 BYTE), 
	"MOD_DT" DATE DEFAULT SYSDATE, 
	"MOD_BY" VARCHAR2(30 BYTE) DEFAULT USER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 131072 NEXT 131072 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA_SMALL" ;
  GRANT SELECT ON "SWB"."CORR_TYPE" TO "T40HC44";
  GRANT UPDATE ON "SWB"."CORR_TYPE" TO "SWB_ADMIN";
  GRANT SELECT ON "SWB"."CORR_TYPE" TO "SWB_ADMIN";
  GRANT INSERT ON "SWB"."CORR_TYPE" TO "SWB_ADMIN";
  GRANT DELETE ON "SWB"."CORR_TYPE" TO "SWB_ADMIN";
  GRANT ALTER ON "SWB"."CORR_TYPE" TO "SWB_ADMIN";
--------------------------------------------------------
--  DDL for Table DOC_TYPE
--------------------------------------------------------

  CREATE TABLE "SWB"."DOC_TYPE" 
   (	"DOCM_TYPE_ID" NUMBER(*,0), 
	"DOCM_TYPE_DESC" VARCHAR2(50 BYTE), 
	"MOD_DT" DATE DEFAULT SYSDATE, 
	"MOD_BY" VARCHAR2(30 BYTE) DEFAULT USER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 131072 NEXT 131072 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA_SMALL" ;
  GRANT SELECT ON "SWB"."DOC_TYPE" TO "T40HC44";
  GRANT UPDATE ON "SWB"."DOC_TYPE" TO "SWB_ADMIN";
  GRANT SELECT ON "SWB"."DOC_TYPE" TO "SWB_ADMIN";
  GRANT INSERT ON "SWB"."DOC_TYPE" TO "SWB_ADMIN";
  GRANT DELETE ON "SWB"."DOC_TYPE" TO "SWB_ADMIN";
  GRANT ALTER ON "SWB"."DOC_TYPE" TO "SWB_ADMIN";
--------------------------------------------------------
--  DDL for Table PRT_METH
--------------------------------------------------------

  CREATE TABLE "SWB"."PRT_METH" 
   (	"PRT_METH_ID" NUMBER(*,0), 
	"PRT_METH_DESC" VARCHAR2(50 BYTE), 
	"MOD_DT" DATE DEFAULT SYSDATE, 
	"MOD_BY" VARCHAR2(30 BYTE) DEFAULT USER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 131072 NEXT 131072 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA_SMALL" ;
  GRANT SELECT ON "SWB"."PRT_METH" TO "T40HC44";
  GRANT UPDATE ON "SWB"."PRT_METH" TO "SWB_ADMIN";
  GRANT SELECT ON "SWB"."PRT_METH" TO "SWB_ADMIN";
  GRANT INSERT ON "SWB"."PRT_METH" TO "SWB_ADMIN";
  GRANT DELETE ON "SWB"."PRT_METH" TO "SWB_ADMIN";
  GRANT ALTER ON "SWB"."PRT_METH" TO "SWB_ADMIN";
--------------------------------------------------------
--  DDL for Table PRT_OPT
--------------------------------------------------------

  CREATE TABLE "SWB"."PRT_OPT" 
   (	"PRT_OPT_ID" NUMBER(*,0), 
	"PRT_OPT_DESC" VARCHAR2(40 BYTE), 
	"MOD_DT" DATE DEFAULT SYSDATE, 
	"MOD_BY" VARCHAR2(30 BYTE) DEFAULT USER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 131072 NEXT 131072 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA_SMALL" ;
  GRANT SELECT ON "SWB"."PRT_OPT" TO "T40HC44";
  GRANT UPDATE ON "SWB"."PRT_OPT" TO "SWB_ADMIN";
  GRANT SELECT ON "SWB"."PRT_OPT" TO "SWB_ADMIN";
  GRANT INSERT ON "SWB"."PRT_OPT" TO "SWB_ADMIN";
  GRANT DELETE ON "SWB"."PRT_OPT" TO "SWB_ADMIN";
  GRANT ALTER ON "SWB"."PRT_OPT" TO "SWB_ADMIN";
--------------------------------------------------------
--  DDL for Table SWB_FORM_REQ_MODE
--------------------------------------------------------

  CREATE TABLE "SWB"."SWB_FORM_REQ_MODE" 
   (	"SWB_USER" CHAR(8 BYTE), 
	"WRK_TYPE_NUM" NUMBER(2,0), 
	"MODE_CD" CHAR(1 BYTE), 
	"CREATED_BY" VARCHAR2(30 BYTE) DEFAULT 'USER', 
	"CREATED_WHEN" DATE DEFAULT SYSDATE, 
	"UPDATED_BY" VARCHAR2(30 BYTE) DEFAULT 'USER', 
	"UPDATED_WHEN" DATE DEFAULT SYSDATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 131072 NEXT 131072 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA_SMALL" ;
  GRANT SELECT ON "SWB"."SWB_FORM_REQ_MODE" TO "T40HC44";
  GRANT SELECT ON "SWB"."SWB_FORM_REQ_MODE" TO "SWB_QUERY";
  GRANT UPDATE ON "SWB"."SWB_FORM_REQ_MODE" TO "SWB_ADMIN";
  GRANT SELECT ON "SWB"."SWB_FORM_REQ_MODE" TO "SWB_ADMIN";
  GRANT INSERT ON "SWB"."SWB_FORM_REQ_MODE" TO "SWB_ADMIN";
  GRANT DELETE ON "SWB"."SWB_FORM_REQ_MODE" TO "SWB_ADMIN";
  GRANT ALTER ON "SWB"."SWB_FORM_REQ_MODE" TO "SWB_ADMIN";
--------------------------------------------------------
--  DDL for Table SWB_WRK_TYPE_IMPL
--------------------------------------------------------

  CREATE TABLE "SWB"."SWB_WRK_TYPE_IMPL" 
   (	"WRK_TYPE_NUM" NUMBER(2,0), 
	"WRK_TYPE_DESC" VARCHAR2(30 BYTE), 
	"CREATED_BY" VARCHAR2(30 BYTE) DEFAULT 'USER', 
	"CREATED_WHEN" DATE DEFAULT SYSDATE, 
	"UPDATED_BY" VARCHAR2(30 BYTE) DEFAULT 'USER', 
	"UPDATED_WHEN" DATE DEFAULT SYSDATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 131072 NEXT 131072 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA_SMALL" ;
  GRANT SELECT ON "SWB"."SWB_WRK_TYPE_IMPL" TO "T40HC44";
  GRANT SELECT ON "SWB"."SWB_WRK_TYPE_IMPL" TO "SWB_QUERY";
  GRANT UPDATE ON "SWB"."SWB_WRK_TYPE_IMPL" TO "SWB_ADMIN";
  GRANT SELECT ON "SWB"."SWB_WRK_TYPE_IMPL" TO "SWB_ADMIN";
  GRANT INSERT ON "SWB"."SWB_WRK_TYPE_IMPL" TO "SWB_ADMIN";
  GRANT DELETE ON "SWB"."SWB_WRK_TYPE_IMPL" TO "SWB_ADMIN";
  GRANT ALTER ON "SWB"."SWB_WRK_TYPE_IMPL" TO "SWB_ADMIN";
--------------------------------------------------------
--  DDL for Index AWD_SRCE_TYPE_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "SWB"."AWD_SRCE_TYPE_PK" ON "SWB"."AWD_SRCE_TYPE" ("NAME") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 131072 NEXT 131072 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA_SMALL" ;
--------------------------------------------------------
--  DDL for Index PK_AWD_WRK_TYPE
--------------------------------------------------------

  CREATE UNIQUE INDEX "SWB"."PK_AWD_WRK_TYPE" ON "SWB"."AWD_WRK_TYPE" ("WRK_TYPE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 131072 NEXT 131072 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "INDX_SMALL" ;
--------------------------------------------------------
--  DDL for Index PK_CORR_PRT_METH_ALLW
--------------------------------------------------------

  CREATE UNIQUE INDEX "SWB"."PK_CORR_PRT_METH_ALLW" ON "SWB"."CORR_PRT_METH_ALLW" ("CORR_TYPE_ID", "PRT_OPT_ID", "PRT_METH_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 131072 NEXT 131072 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "INDX_SMALL" ;
--------------------------------------------------------
--  DDL for Index PK_CORR_PRT_OPT_ALLW
--------------------------------------------------------

  CREATE UNIQUE INDEX "SWB"."PK_CORR_PRT_OPT_ALLW" ON "SWB"."CORR_PRT_OPT_ALLW" ("CORR_TYPE_ID", "PRT_OPT_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 131072 NEXT 131072 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "INDX_SMALL" ;
--------------------------------------------------------
--  DDL for Index PK_CORR_TYPE
--------------------------------------------------------

  CREATE UNIQUE INDEX "SWB"."PK_CORR_TYPE" ON "SWB"."CORR_TYPE" ("CORR_TYPE_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 131072 NEXT 131072 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "INDX_SMALL" ;
--------------------------------------------------------
--  DDL for Index PK_DOC_TYPE
--------------------------------------------------------

  CREATE UNIQUE INDEX "SWB"."PK_DOC_TYPE" ON "SWB"."DOC_TYPE" ("DOCM_TYPE_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 131072 NEXT 131072 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "INDX_SMALL" ;
--------------------------------------------------------
--  DDL for Index PK_PRT_METH
--------------------------------------------------------

  CREATE UNIQUE INDEX "SWB"."PK_PRT_METH" ON "SWB"."PRT_METH" ("PRT_METH_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 131072 NEXT 131072 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "INDX_SMALL" ;
--------------------------------------------------------
--  DDL for Index PK_PRT_OPT
--------------------------------------------------------

  CREATE UNIQUE INDEX "SWB"."PK_PRT_OPT" ON "SWB"."PRT_OPT" ("PRT_OPT_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 131072 NEXT 131072 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "INDX_SMALL" ;
--------------------------------------------------------
--  DDL for Index PK_SWB_FORM_REQ_MODE
--------------------------------------------------------

  CREATE UNIQUE INDEX "SWB"."PK_SWB_FORM_REQ_MODE" ON "SWB"."SWB_FORM_REQ_MODE" ("SWB_USER", "WRK_TYPE_NUM") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 131072 NEXT 131072 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "INDX_SMALL" ;
--------------------------------------------------------
--  DDL for Index PK_SWB_WRK_TYPE_IMPL
--------------------------------------------------------

  CREATE UNIQUE INDEX "SWB"."PK_SWB_WRK_TYPE_IMPL" ON "SWB"."SWB_WRK_TYPE_IMPL" ("WRK_TYPE_NUM") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 131072 NEXT 131072 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "INDX_SMALL" ;
--------------------------------------------------------
--  DDL for Index AWD_SRCE_TYPE_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "SWB"."AWD_SRCE_TYPE_PK" ON "SWB"."AWD_SRCE_TYPE" ("NAME") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 131072 NEXT 131072 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA_SMALL" ;
--------------------------------------------------------
--  DDL for Index PK_AWD_WRK_TYPE
--------------------------------------------------------

  CREATE UNIQUE INDEX "SWB"."PK_AWD_WRK_TYPE" ON "SWB"."AWD_WRK_TYPE" ("WRK_TYPE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 131072 NEXT 131072 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "INDX_SMALL" ;
--------------------------------------------------------
--  DDL for Index PK_CORR_PRT_METH_ALLW
--------------------------------------------------------

  CREATE UNIQUE INDEX "SWB"."PK_CORR_PRT_METH_ALLW" ON "SWB"."CORR_PRT_METH_ALLW" ("CORR_TYPE_ID", "PRT_OPT_ID", "PRT_METH_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 131072 NEXT 131072 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "INDX_SMALL" ;
--------------------------------------------------------
--  DDL for Index PK_CORR_PRT_OPT_ALLW
--------------------------------------------------------

  CREATE UNIQUE INDEX "SWB"."PK_CORR_PRT_OPT_ALLW" ON "SWB"."CORR_PRT_OPT_ALLW" ("CORR_TYPE_ID", "PRT_OPT_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 131072 NEXT 131072 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "INDX_SMALL" ;
--------------------------------------------------------
--  DDL for Index PK_CORR_TYPE
--------------------------------------------------------

  CREATE UNIQUE INDEX "SWB"."PK_CORR_TYPE" ON "SWB"."CORR_TYPE" ("CORR_TYPE_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 131072 NEXT 131072 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "INDX_SMALL" ;
--------------------------------------------------------
--  DDL for Index PK_DOC_TYPE
--------------------------------------------------------

  CREATE UNIQUE INDEX "SWB"."PK_DOC_TYPE" ON "SWB"."DOC_TYPE" ("DOCM_TYPE_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 131072 NEXT 131072 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "INDX_SMALL" ;
--------------------------------------------------------
--  DDL for Index PK_PRT_METH
--------------------------------------------------------

  CREATE UNIQUE INDEX "SWB"."PK_PRT_METH" ON "SWB"."PRT_METH" ("PRT_METH_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 131072 NEXT 131072 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "INDX_SMALL" ;
--------------------------------------------------------
--  DDL for Index PK_PRT_OPT
--------------------------------------------------------

  CREATE UNIQUE INDEX "SWB"."PK_PRT_OPT" ON "SWB"."PRT_OPT" ("PRT_OPT_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 131072 NEXT 131072 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "INDX_SMALL" ;
--------------------------------------------------------
--  DDL for Index PK_SWB_FORM_REQ_MODE
--------------------------------------------------------

  CREATE UNIQUE INDEX "SWB"."PK_SWB_FORM_REQ_MODE" ON "SWB"."SWB_FORM_REQ_MODE" ("SWB_USER", "WRK_TYPE_NUM") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 131072 NEXT 131072 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "INDX_SMALL" ;
--------------------------------------------------------
--  DDL for Index PK_SWB_WRK_TYPE_IMPL
--------------------------------------------------------

  CREATE UNIQUE INDEX "SWB"."PK_SWB_WRK_TYPE_IMPL" ON "SWB"."SWB_WRK_TYPE_IMPL" ("WRK_TYPE_NUM") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 131072 NEXT 131072 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "INDX_SMALL" ;
--------------------------------------------------------
--  Constraints for Table AWD_SRCE_TYPE
--------------------------------------------------------

  ALTER TABLE "SWB"."AWD_SRCE_TYPE" MODIFY ("NAME" NOT NULL ENABLE);
  ALTER TABLE "SWB"."AWD_SRCE_TYPE" MODIFY ("DESC" NOT NULL ENABLE);
  ALTER TABLE "SWB"."AWD_SRCE_TYPE" ADD CONSTRAINT "AWD_SRCE_TYPE_PK" PRIMARY KEY ("NAME")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 131072 NEXT 131072 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA_SMALL"  ENABLE;
--------------------------------------------------------
--  Constraints for Table AWD_SRCE_TYPE_063013
--------------------------------------------------------

  ALTER TABLE "SWB"."AWD_SRCE_TYPE_063013" MODIFY ("NAME" NOT NULL ENABLE);
  ALTER TABLE "SWB"."AWD_SRCE_TYPE_063013" MODIFY ("DESC" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table AWD_WRK_TYPE
--------------------------------------------------------

  ALTER TABLE "SWB"."AWD_WRK_TYPE" MODIFY ("WRK_TYPE" NOT NULL ENABLE);
  ALTER TABLE "SWB"."AWD_WRK_TYPE" MODIFY ("WRK_TYPE_DESC" NOT NULL ENABLE);
  ALTER TABLE "SWB"."AWD_WRK_TYPE" MODIFY ("MOD_DT" NOT NULL ENABLE);
  ALTER TABLE "SWB"."AWD_WRK_TYPE" MODIFY ("MOD_BY" NOT NULL ENABLE);
  ALTER TABLE "SWB"."AWD_WRK_TYPE" ADD CONSTRAINT "PK_AWD_WRK_TYPE" PRIMARY KEY ("WRK_TYPE")
  USING INDEX "SWB"."PK_AWD_WRK_TYPE"  ENABLE;
--------------------------------------------------------
--  Constraints for Table CORR_PRT_METH_ALLW
--------------------------------------------------------

  ALTER TABLE "SWB"."CORR_PRT_METH_ALLW" MODIFY ("CORR_TYPE_ID" NOT NULL ENABLE);
  ALTER TABLE "SWB"."CORR_PRT_METH_ALLW" MODIFY ("PRT_OPT_ID" NOT NULL ENABLE);
  ALTER TABLE "SWB"."CORR_PRT_METH_ALLW" MODIFY ("PRT_METH_ID" NOT NULL ENABLE);
  ALTER TABLE "SWB"."CORR_PRT_METH_ALLW" ADD CONSTRAINT "PK_CORR_PRT_METH_ALLW" PRIMARY KEY ("CORR_TYPE_ID", "PRT_OPT_ID", "PRT_METH_ID")
  USING INDEX "SWB"."PK_CORR_PRT_METH_ALLW"  ENABLE;
--------------------------------------------------------
--  Constraints for Table CORR_PRT_OPT_ALLW
--------------------------------------------------------

  ALTER TABLE "SWB"."CORR_PRT_OPT_ALLW" MODIFY ("CORR_TYPE_ID" NOT NULL ENABLE);
  ALTER TABLE "SWB"."CORR_PRT_OPT_ALLW" MODIFY ("PRT_OPT_ID" NOT NULL ENABLE);
  ALTER TABLE "SWB"."CORR_PRT_OPT_ALLW" MODIFY ("VCSR_PRT_OPT_IND" NOT NULL ENABLE);
  ALTER TABLE "SWB"."CORR_PRT_OPT_ALLW" MODIFY ("CHG_ALLW_IND" NOT NULL ENABLE);
  ALTER TABLE "SWB"."CORR_PRT_OPT_ALLW" MODIFY ("DFLT_PRT_OPT_IND" NOT NULL ENABLE);
  ALTER TABLE "SWB"."CORR_PRT_OPT_ALLW" MODIFY ("MOD_DT" NOT NULL ENABLE);
  ALTER TABLE "SWB"."CORR_PRT_OPT_ALLW" MODIFY ("MOD_BY" NOT NULL ENABLE);
  ALTER TABLE "SWB"."CORR_PRT_OPT_ALLW" ADD CONSTRAINT "PK_CORR_PRT_OPT_ALLW" PRIMARY KEY ("CORR_TYPE_ID", "PRT_OPT_ID")
  USING INDEX "SWB"."PK_CORR_PRT_OPT_ALLW"  ENABLE;
--------------------------------------------------------
--  Constraints for Table CORR_TYPE
--------------------------------------------------------

  ALTER TABLE "SWB"."CORR_TYPE" MODIFY ("CORR_TYPE_ID" NOT NULL ENABLE);
  ALTER TABLE "SWB"."CORR_TYPE" MODIFY ("WRK_TYPE" NOT NULL ENABLE);
  ALTER TABLE "SWB"."CORR_TYPE" MODIFY ("DOCM_TYPE_ID" NOT NULL ENABLE);
  ALTER TABLE "SWB"."CORR_TYPE" MODIFY ("CORR_DESC" NOT NULL ENABLE);
  ALTER TABLE "SWB"."CORR_TYPE" MODIFY ("DFS_INTG_IND" NOT NULL ENABLE);
  ALTER TABLE "SWB"."CORR_TYPE" MODIFY ("MOD_DT" NOT NULL ENABLE);
  ALTER TABLE "SWB"."CORR_TYPE" MODIFY ("MOD_BY" NOT NULL ENABLE);
  ALTER TABLE "SWB"."CORR_TYPE" ADD CONSTRAINT "PK_CORR_TYPE" PRIMARY KEY ("CORR_TYPE_ID")
  USING INDEX "SWB"."PK_CORR_TYPE"  ENABLE;
--------------------------------------------------------
--  Constraints for Table DOC_TYPE
--------------------------------------------------------

  ALTER TABLE "SWB"."DOC_TYPE" MODIFY ("DOCM_TYPE_ID" NOT NULL ENABLE);
  ALTER TABLE "SWB"."DOC_TYPE" MODIFY ("DOCM_TYPE_DESC" NOT NULL ENABLE);
  ALTER TABLE "SWB"."DOC_TYPE" MODIFY ("MOD_DT" NOT NULL ENABLE);
  ALTER TABLE "SWB"."DOC_TYPE" MODIFY ("MOD_BY" NOT NULL ENABLE);
  ALTER TABLE "SWB"."DOC_TYPE" ADD CONSTRAINT "PK_DOC_TYPE" PRIMARY KEY ("DOCM_TYPE_ID")
  USING INDEX "SWB"."PK_DOC_TYPE"  ENABLE;
--------------------------------------------------------
--  Constraints for Table PRT_METH
--------------------------------------------------------

  ALTER TABLE "SWB"."PRT_METH" MODIFY ("PRT_METH_ID" NOT NULL ENABLE);
  ALTER TABLE "SWB"."PRT_METH" MODIFY ("PRT_METH_DESC" NOT NULL ENABLE);
  ALTER TABLE "SWB"."PRT_METH" MODIFY ("MOD_DT" NOT NULL ENABLE);
  ALTER TABLE "SWB"."PRT_METH" MODIFY ("MOD_BY" NOT NULL ENABLE);
  ALTER TABLE "SWB"."PRT_METH" ADD CONSTRAINT "PK_PRT_METH" PRIMARY KEY ("PRT_METH_ID")
  USING INDEX "SWB"."PK_PRT_METH"  ENABLE;
--------------------------------------------------------
--  Constraints for Table PRT_OPT
--------------------------------------------------------

  ALTER TABLE "SWB"."PRT_OPT" MODIFY ("PRT_OPT_ID" NOT NULL ENABLE);
  ALTER TABLE "SWB"."PRT_OPT" MODIFY ("PRT_OPT_DESC" NOT NULL ENABLE);
  ALTER TABLE "SWB"."PRT_OPT" MODIFY ("MOD_DT" NOT NULL ENABLE);
  ALTER TABLE "SWB"."PRT_OPT" MODIFY ("MOD_BY" NOT NULL ENABLE);
  ALTER TABLE "SWB"."PRT_OPT" ADD CONSTRAINT "PK_PRT_OPT" PRIMARY KEY ("PRT_OPT_ID")
  USING INDEX "SWB"."PK_PRT_OPT"  ENABLE;
--------------------------------------------------------
--  Constraints for Table SWB_FORM_REQ_MODE
--------------------------------------------------------

  ALTER TABLE "SWB"."SWB_FORM_REQ_MODE" MODIFY ("SWB_USER" NOT NULL ENABLE);
  ALTER TABLE "SWB"."SWB_FORM_REQ_MODE" MODIFY ("WRK_TYPE_NUM" NOT NULL ENABLE);
  ALTER TABLE "SWB"."SWB_FORM_REQ_MODE" ADD CONSTRAINT "PK_SWB_FORM_REQ_MODE" PRIMARY KEY ("SWB_USER", "WRK_TYPE_NUM")
  USING INDEX "SWB"."PK_SWB_FORM_REQ_MODE"  ENABLE;
--------------------------------------------------------
--  Constraints for Table SWB_WRK_TYPE_IMPL
--------------------------------------------------------

  ALTER TABLE "SWB"."SWB_WRK_TYPE_IMPL" ADD CONSTRAINT "PK_SWB_WRK_TYPE_IMPL" PRIMARY KEY ("WRK_TYPE_NUM")
  USING INDEX "SWB"."PK_SWB_WRK_TYPE_IMPL"  ENABLE;
  ALTER TABLE "SWB"."SWB_WRK_TYPE_IMPL" MODIFY ("WRK_TYPE_NUM" NOT NULL ENABLE);
--------------------------------------------------------
--  Ref Constraints for Table CORR_PRT_METH_ALLW
--------------------------------------------------------

  ALTER TABLE "SWB"."CORR_PRT_METH_ALLW" ADD CONSTRAINT "FK_CPMA_PRT_METH" FOREIGN KEY ("PRT_METH_ID")
	  REFERENCES "SWB"."PRT_METH" ("PRT_METH_ID") ENABLE;
  ALTER TABLE "SWB"."CORR_PRT_METH_ALLW" ADD CONSTRAINT "FK_CPMA_CORR_PRT_OPT_ALLW" FOREIGN KEY ("CORR_TYPE_ID", "PRT_OPT_ID")
	  REFERENCES "SWB"."CORR_PRT_OPT_ALLW" ("CORR_TYPE_ID", "PRT_OPT_ID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table CORR_PRT_OPT_ALLW
--------------------------------------------------------

  ALTER TABLE "SWB"."CORR_PRT_OPT_ALLW" ADD CONSTRAINT "FK_CPOA_PRT_OPT" FOREIGN KEY ("PRT_OPT_ID")
	  REFERENCES "SWB"."PRT_OPT" ("PRT_OPT_ID") ENABLE;
  ALTER TABLE "SWB"."CORR_PRT_OPT_ALLW" ADD CONSTRAINT "FK_CPOA_CORR_TYPE" FOREIGN KEY ("CORR_TYPE_ID")
	  REFERENCES "SWB"."CORR_TYPE" ("CORR_TYPE_ID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table CORR_TYPE
--------------------------------------------------------

  ALTER TABLE "SWB"."CORR_TYPE" ADD CONSTRAINT "FK_CT_DOC_TYPE" FOREIGN KEY ("DOCM_TYPE_ID")
	  REFERENCES "SWB"."DOC_TYPE" ("DOCM_TYPE_ID") ENABLE;
  ALTER TABLE "SWB"."CORR_TYPE" ADD CONSTRAINT "FK_CT_AWD_WRK_TYPE" FOREIGN KEY ("WRK_TYPE")
	  REFERENCES "SWB"."AWD_WRK_TYPE" ("WRK_TYPE") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table SWB_FORM_REQ_MODE
--------------------------------------------------------

  ALTER TABLE "SWB"."SWB_FORM_REQ_MODE" ADD CONSTRAINT "FK_SFRM_SWTI" FOREIGN KEY ("WRK_TYPE_NUM")
	  REFERENCES "SWB"."SWB_WRK_TYPE_IMPL" ("WRK_TYPE_NUM") ENABLE;
